export const aiAgents = [
    {
        id: 5,
        name: "Graphic Design Ace",
        category: "Graphic Design",
        description: "Create stunning visuals and branding.",
        price: "$60/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 6,
        name: "Data Analyst Pro",
        category: "Data Analysis",
        description: "Transform raw data into actionable insights.",
        price: "$80/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 7,
        name: "Video Editing Ninja",
        category: "Video Production",
        description: "Edit videos with a professional touch.",
        price: "$70/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 8,
        name: "Email Marketing Guru",
        category: "Marketing",
        description: "Craft effective email campaigns that convert.",
        price: "$50/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 9,
        name: "Copywriting Specialist",
        category: "Content Creation",
        description: "Write persuasive copy that sells.",
        price: "$0.10/word",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 10,
        name: "App Development Pro",
        category: "App Development",
        description: "Build user-friendly mobile applications.",
        price: "$100/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 11,
        name: "UX/UI Designer",
        category: "Design",
        description: "Enhance user experience with innovative designs.",
        price: "$70/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 12,
        name: "Virtual Assistant",
        category: "Administrative",
        description: "Manage schedules and administrative tasks.",
        price: "$25/hour",
        image: "https://via.placeholder.com/150",
        popularity: 3,
    },
    {
        id: 13,
        name: "E-commerce Specialist",
        category: "E-commerce",
        description: "Optimize your online store for sales.",
        price: "$100/project",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 14,
        name: "Translation Expert",
        category: "Translation",
        description: "Translate documents with accuracy.",
        price: "$0.08/word",
        image: "https://via.placeholder.com/150",
        popularity: 3,
    },
    {
        id: 15,
        name: "Blockchain Consultant",
        category: "Consulting",
        description: "Provide insights into blockchain technology.",
        price: "$150/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 16,
        name: "Market Research Analyst",
        category: "Research",
        description: "Gather and analyze market data.",
        price: "$90/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 17,
        name: "Online Course Creator",
        category: "Education",
        description: "Design and launch engaging online courses.",
        price: "$80/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 18,
        name: "IT Support Specialist",
        category: "IT Support",
        description: "Provide technical support and troubleshooting.",
        price: "$40/hour",
        image: "https://via.placeholder.com/150",
        popularity: 3,
    },
    {
        id: 19,
        name: "Podcast Producer",
        category: "Audio Production",
        description: "Produce and edit high-quality podcasts.",
        price: "$60/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 20,
        name: "Photo Editing Wizard",
        category: "Photography",
        description: "Edit and enhance photos like a pro.",
        price: "$50/hour",
        image: "https://via.placeholder.com/150",
        popularity: 3,
    },
    {
        id: 21,
        name: "HR Consultant",
        category: "Consulting",
        description: "Provide human resources support and guidance.",
        price: "$90/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 22,
        name: "Sales Funnel Expert",
        category: "Sales",
        description: "Create optimized sales funnels that convert.",
        price: "$120/project",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 23,
        name: "Legal Consultant",
        category: "Legal",
        description: "Provide legal advice and document preparation.",
        price: "$150/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 24,
        name: "Event Planner",
        category: "Event Management",
        description: "Plan and coordinate memorable events.",
        price: "$70/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 25,
        name: "Fitness Coach",
        category: "Health & Fitness",
        description: "Personalized training plans to achieve your goals.",
        price: "$50/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 26,
        name: "Voiceover Artist",
        category: "Audio Production",
        description: "Professional voiceovers for your projects.",
        price: "$100/hour",
        image: "https://via.placeholder.com/150",
        popularity: 3,
    },
    {
        id: 27,
        name: "Game Developer",
        category: "Game Development",
        description: "Create engaging and interactive games.",
        price: "$100/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
    {
        id: 28,
        name: "Resume Writer",
        category: "Career Services",
        description: "Craft impactful resumes that stand out.",
        price: "$50/resume",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 29,
        name: "Influencer Marketing Expert",
        category: "Marketing",
        description: "Connect brands with influencers for campaigns.",
        price: "$80/hour",
        image: "https://via.placeholder.com/150",
        popularity: 4,
    },
    {
        id: 30,
        name: "Brand Strategist",
        category: "Branding",
        description: "Develop and enhance brand identity.",
        price: "$90/hour",
        image: "https://via.placeholder.com/150",
        popularity: 5,
    },
];
